import type { PathAnalysisResult, CriblConfig } from '@/types/logonboard';

// Cribl Stream Configuration Generator
// Based on: https://docs.cribl.io/stream/packs/

export function generateCriblConfig(results: PathAnalysisResult[]): CriblConfig {
  return {
    routes: generateRoutes(results),
    pipelines: generatePipelines(results),
    packs: generatePacks(results),
  };
}

function generateRoutes(results: PathAnalysisResult[]): string {
  const routes = {
    id: 'logonboard',
    conf: {
      routes: results.map((result, index) => ({
        id: `route_${result.sourcetype.replace(/[^a-zA-Z0-9]/g, '_')}`,
        name: `Route for ${result.sourcetype}`,
        filter: `__inputId.startsWith('${result.category}')`,
        pipeline: `pipeline_${result.category}`,
        output: getDefaultOutput(result),
        final: false,
        disabled: false,
        order: index,
      })),
    },
  };

  const yaml = [
    '# Cribl Stream Routes Configuration',
    '# Generated by LogOnboard-AI',
    '# Docs: https://docs.cribl.io/stream/routes/',
    '',
    `id: ${routes.id}`,
    'routes:',
  ];

  for (const route of routes.conf.routes) {
    yaml.push(`  - id: ${route.id}`);
    yaml.push(`    name: "${route.name}"`);
    yaml.push(`    filter: "${route.filter}"`);
    yaml.push(`    pipeline: ${route.pipeline}`);
    yaml.push(`    output: ${route.output}`);
    yaml.push(`    final: ${route.final}`);
    yaml.push(`    disabled: ${route.disabled}`);
    yaml.push('');
  }

  return yaml.join('\n');
}

function generatePipelines(results: PathAnalysisResult[]): string {
  const categories = [...new Set(results.map((r) => r.category))];

  const yaml = [
    '# Cribl Stream Pipelines Configuration',
    '# Generated by LogOnboard-AI',
    '# Docs: https://docs.cribl.io/stream/pipelines/',
    '',
  ];

  for (const category of categories) {
    yaml.push(`# Pipeline for ${category} logs`);
    yaml.push(`id: pipeline_${category}`);
    yaml.push('conf:');
    yaml.push('  asyncFuncTimeout: 1000');
    yaml.push('  functions:');
    yaml.push('');
    yaml.push('    # Add source metadata');
    yaml.push('    - id: eval');
    yaml.push('      filter: "true"');
    yaml.push('      disabled: false');
    yaml.push('      conf:');
    yaml.push('        add:');
    yaml.push(`          - name: category`);
    yaml.push(`            value: "'${category}'"`);
    yaml.push('          - name: logonboard_processed');
    yaml.push("            value: 'true'");
    yaml.push('');

    // Add category-specific processing
    if (category === 'web') {
      yaml.push('    # Parse web access logs');
      yaml.push('    - id: regex_extract');
      yaml.push('      filter: "true"');
      yaml.push('      disabled: false');
      yaml.push('      conf:');
      yaml.push("        source: '_raw'");
      yaml.push('        iterations: 100');
      yaml.push(
        '        regex: /^(?<client_ip>[\\S]+) \\S+ (?<user>[\\S]+) \\[(?<timestamp>[^\\]]+)\\] "(?<method>[A-Z]+) (?<uri>[^"]*)" (?<status>\\d+) (?<bytes>\\d+)/'
      );
      yaml.push('');
    }

    if (category === 'security') {
      yaml.push('    # Mask sensitive data');
      yaml.push('    - id: mask');
      yaml.push('      filter: "true"');
      yaml.push('      disabled: false');
      yaml.push('      conf:');
      yaml.push('        rules:');
      yaml.push('          - matchRegex: /\\b\\d{3}-\\d{2}-\\d{4}\\b/g');
      yaml.push('            replaceExpr: "\'XXX-XX-XXXX\'"');
      yaml.push('');
    }

    yaml.push('---');
    yaml.push('');
  }

  return yaml.join('\n');
}

function generatePacks(results: PathAnalysisResult[]): string {
  const categories = [...new Set(results.map((r) => r.category))];
  const sourcetypes = [...new Set(results.map((r) => r.sourcetype))];

  const pack = {
    id: 'logonboard-pack',
    conf: {
      version: '1.0.0',
      displayName: 'LogOnboard-AI Generated Pack',
      description: `Auto-generated pack for ${sourcetypes.length} log types`,
      tags: ['logonboard', 'auto-generated', ...categories],
      author: 'LogOnboard-AI',
    },
  };

  const yaml = [
    '# Cribl Stream Pack Configuration',
    '# Generated by LogOnboard-AI',
    '# Docs: https://docs.cribl.io/stream/packs/',
    '',
    '# Pack Manifest (pack.yml)',
    `id: ${pack.id}`,
    'conf:',
    `  version: "${pack.conf.version}"`,
    `  displayName: "${pack.conf.displayName}"`,
    `  description: "${pack.conf.description}"`,
    '  tags:',
    ...pack.conf.tags.map((t) => `    - ${t}`),
    `  author: "${pack.conf.author}"`,
    '',
    '# Included Components:',
    '# - Routes: logonboard routes',
    '# - Pipelines:',
    ...categories.map((c) => `#   - pipeline_${c}`),
    '',
    '# Quick Start:',
    '# 1. Import this pack via Packs > Add Pack > Import from file',
    '# 2. Configure your Sources to send data to this pack',
    '# 3. Configure Destinations (Splunk, Elastic, S3, etc.)',
    '',
    '# Destination Recommendations:',
  ];

  // Add destination recommendations based on log types
  if (results.some((r) => r.category === 'security')) {
    yaml.push('# Security logs: SIEM destination (Splunk, Sentinel, QRadar)');
  }
  if (results.some((r) => r.category === 'web')) {
    yaml.push('# Web logs: Object storage + SIEM for analysis');
  }
  if (results.some((r) => r.category === 'application')) {
    yaml.push('# Application logs: Elasticsearch/OpenSearch for search');
  }

  return yaml.join('\n');
}

function getDefaultOutput(result: PathAnalysisResult): string {
  // Recommend output based on category
  const outputMap: Record<string, string> = {
    security: 'siem_output',
    web: 'splunk_output',
    os: 'siem_output',
    application: 'elastic_output',
    database: 'elastic_output',
    container: 's3_output',
    network: 'siem_output',
    cloud: 's3_output',
  };

  return outputMap[result.category] || 'default_output';
}
