import type {
  PathAnalysisResult,
  SensitiveFinding,
  ElasticConfig,
  AnalyzeOptions,
  LogSampleAnalysis,
} from '@/types/logonboard';

// Elastic Stack Config Generator - Creates Filebeat, Logstash, and Ingest Pipeline configs

export function generateElasticConfigs(
  analysisResults: PathAnalysisResult[],
  sensitiveFindings: SensitiveFinding[],
  options: AnalyzeOptions,
  sampleAnalysis?: LogSampleAnalysis
): ElasticConfig {
  const filebeatYml = generateFilebeatYml(analysisResults, sampleAnalysis);
  const logstashConf = generateLogstashConf(analysisResults, sampleAnalysis);
  const ingestPipeline = generateIngestPipeline(analysisResults, sensitiveFindings, sampleAnalysis);
  const indexTemplate = generateIndexTemplate(analysisResults, sampleAnalysis);

  return {
    filebeatYml,
    logstashConf,
    ingestPipeline,
    indexTemplate,
  };
}

function generateFilebeatYml(
  results: PathAnalysisResult[],
  sampleAnalysis?: LogSampleAnalysis
): string {
  const lines: string[] = [
    '# filebeat.yml - Generated by LogOnboard-AI',
    '#',
    '# DEPLOYMENT: Filebeat Agent',
    '# Deploy this file to each log source endpoint',
    '# Path: /etc/filebeat/filebeat.yml',
    '#',
    '# Installation:',
    '# curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.19.0-linux-x86_64.tar.gz',
    '# tar xzvf filebeat-8.19.0-linux-x86_64.tar.gz',
    '#',
    '# Ref: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html',
    '',
  ];

  // Add platform/format detection info if available
  if (sampleAnalysis) {
    lines.push(`# Detected Platform: ${sampleAnalysis.detectedPlatform.toUpperCase()}`);
    lines.push(`# Detected Format: ${sampleAnalysis.detectedFormat.toUpperCase()}`);
    lines.push('');
  }

  lines.push('# ==================== Filebeat inputs ====================');
  lines.push('');
  lines.push('filebeat.inputs:');

  for (const result of results) {
    const isWindowsPath = /^[a-z]:\\/i.test(result.path);
    const normalizedPath = isWindowsPath ? result.path.replace(/\\/g, '/') : result.path;

    lines.push('');
    lines.push('  # Input for ' + result.category);
    lines.push('  - type: log');
    lines.push('    enabled: true');
    lines.push('    paths:');
    lines.push(`      - "${normalizedPath}"`);
    lines.push('    fields:');
    lines.push(`      log_type: ${result.sourcetype}`);
    lines.push(`      category: ${result.category}`);
    if (sampleAnalysis) {
      lines.push(`      platform: ${sampleAnalysis.detectedPlatform}`);
      lines.push(`      format: ${sampleAnalysis.detectedFormat}`);
    }
    lines.push('    fields_under_root: false');

    // Add multiline config for non-JSON formats
    if (sampleAnalysis?.detectedFormat !== 'json') {
      lines.push('    # Multiline configuration');
      lines.push('    multiline.type: pattern');
      lines.push('    multiline.pattern: "^\\\\["'); // Default: lines starting with [
      lines.push('    multiline.negate: true');
      lines.push('    multiline.match: after');
    }

    // Add JSON parsing for JSON logs
    if (sampleAnalysis?.detectedFormat === 'json') {
      lines.push('    # JSON parsing');
      lines.push('    json.keys_under_root: true');
      lines.push('    json.add_error_key: true');
      lines.push('    json.message_key: message');
    }

    if (result.confidence === 'low') {
      lines.push('    # WARNING: Low confidence match - please verify configuration');
    }

    if (isWindowsPath) {
      lines.push('    # NOTE: Install Filebeat on Windows host');
      lines.push('    # Ensure Filebeat service has read access to the log directory');
    }
  }

  lines.push('');
  lines.push('# ==================== Elasticsearch Output ====================');
  lines.push('');
  lines.push('output.elasticsearch:');
  lines.push('  hosts: ["localhost:9200"]');
  lines.push('  # Uncomment if using authentication');
  lines.push('  # username: "elastic"');
  lines.push('  # password: "changeme"');
  lines.push('  # API key authentication (recommended)');
  lines.push('  # api_key: "id:api_key"');
  lines.push('  ');
  lines.push('  # Index naming');
  lines.push('  indices:');

  // Group by sourcetype for index routing
  const sourcetypeGroups = new Map<string, PathAnalysisResult[]>();
  for (const result of results) {
    if (!sourcetypeGroups.has(result.sourcetype)) {
      sourcetypeGroups.set(result.sourcetype, []);
    }
    sourcetypeGroups.get(result.sourcetype)!.push(result);
  }

  for (const [sourcetype] of sourcetypeGroups) {
    lines.push(`    - index: "filebeat-${sourcetype}-%{+yyyy.MM.dd}"`);
    lines.push(`      when.equals:`);
    lines.push(`        fields.log_type: "${sourcetype}"`);
  }

  lines.push('');
  lines.push('# ==================== Processors ====================');
  lines.push('');
  lines.push('processors:');
  lines.push('  - add_host_metadata:');
  lines.push('      when.not.contains.tags: forwarded');
  lines.push('  - add_cloud_metadata: ~');
  lines.push('  - add_docker_metadata: ~');

  lines.push('');
  lines.push('# ==================== Logging ====================');
  lines.push('');
  lines.push('logging.level: info');
  lines.push('logging.to_files: true');
  lines.push('logging.files:');
  lines.push('  path: /var/log/filebeat');
  lines.push('  name: filebeat');
  lines.push('  keepfiles: 7');
  lines.push('  permissions: 0644');

  return lines.join('\n');
}

function generateLogstashConf(
  results: PathAnalysisResult[],
  sampleAnalysis?: LogSampleAnalysis
): string {
  const lines: string[] = [
    '# logstash.conf - Generated by LogOnboard-AI',
    '#',
    '# DEPLOYMENT: Logstash Data Processing Pipeline',
    '# Deploy this file to Logstash instances',
    '# Path: /etc/logstash/conf.d/logonboard.conf',
    '#',
    '# Installation:',
    '# wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg',
    '# sudo apt-get install logstash',
    '#',
    '# Ref: https://www.elastic.co/guide/en/logstash/current/configuration.html',
    '',
  ];

  if (sampleAnalysis) {
    lines.push(`# Detected Platform: ${sampleAnalysis.detectedPlatform.toUpperCase()}`);
    lines.push(`# Detected Format: ${sampleAnalysis.detectedFormat.toUpperCase()}`);
    lines.push('');
  }

  // Input section
  lines.push('input {');
  lines.push('  beats {');
  lines.push('    port => 5044');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Filter section
  lines.push('filter {');

  // Group by sourcetype
  const sourcetypeGroups = new Map<string, PathAnalysisResult[]>();
  for (const result of results) {
    if (!sourcetypeGroups.has(result.sourcetype)) {
      sourcetypeGroups.set(result.sourcetype, []);
    }
    sourcetypeGroups.get(result.sourcetype)!.push(result);
  }

  for (const [sourcetype, sourcetypeResults] of sourcetypeGroups) {
    const result = sourcetypeResults[0]; // Use first result as representative

    lines.push(`  # Processing for ${result.category}`);
    lines.push(`  if [fields][log_type] == "${sourcetype}" {`);

    // Add format-specific parsing
    if (sampleAnalysis?.detectedFormat === 'json') {
      lines.push('    # JSON parsing');
      lines.push('    json {');
      lines.push('      source => "message"');
      lines.push('      target => "parsed"');
      lines.push('    }');
    } else if (sampleAnalysis?.detectedFormat === 'syslog') {
      lines.push('    # Syslog parsing');
      lines.push('    grok {');
      lines.push('      match => { "message" => "%{SYSLOGBASE} %{GREEDYDATA:syslog_message}" }');
      lines.push('    }');
    } else if (sampleAnalysis?.detectedFormat === 'apache') {
      lines.push('    # Apache access log parsing');
      lines.push('    grok {');
      lines.push('      match => { "message" => "%{COMBINEDAPACHELOG}" }');
      lines.push('    }');
    } else if (sampleAnalysis?.detectedFormat === 'cef') {
      lines.push('    # CEF (Common Event Format) parsing');
      lines.push('    grok {');
      lines.push(
        '      match => { "message" => "CEF:%{INT:cef_version}\\|%{DATA:cef_device_vendor}\\|%{DATA:cef_device_product}\\|%{DATA:cef_device_version}\\|%{DATA:cef_signature_id}\\|%{DATA:cef_name}\\|%{DATA:cef_severity}\\|%{GREEDYDATA:cef_extension}" }'
      );
      lines.push('    }');
    } else {
      // Generic grok pattern
      lines.push('    # Generic pattern - customize based on your log format');
      lines.push('    grok {');
      lines.push(
        '      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}" }'
      );
      lines.push('    }');
    }

    // Timestamp parsing
    if (sampleAnalysis?.timeFormat) {
      const logstashTimeFormat = convertSplunkToLogstashTimeFormat(sampleAnalysis.timeFormat);
      lines.push('    ');
      lines.push('    # Timestamp parsing');
      lines.push('    date {');
      lines.push('      match => [ "timestamp", "' + logstashTimeFormat + '" ]');
      lines.push('      target => "@timestamp"');
      lines.push('    }');
    }

    // Add custom fields
    lines.push('    ');
    lines.push('    # Add custom fields');
    lines.push('    mutate {');
    lines.push('      add_field => {');
    lines.push(`        "sourcetype" => "${sourcetype}"`);
    lines.push(`        "index_name" => "${result.index}"`);
    lines.push('      }');
    lines.push('    }');

    lines.push('  }');
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  // Output section
  lines.push('output {');
  lines.push('  elasticsearch {');
  lines.push('    hosts => ["localhost:9200"]');
  lines.push('    # Uncomment if using authentication');
  lines.push('    # user => "elastic"');
  lines.push('    # password => "changeme"');
  lines.push('    ');
  lines.push('    # Index routing based on sourcetype');
  lines.push('    index => "logstash-%{[fields][log_type]}-%{+YYYY.MM.dd}"');
  lines.push('  }');
  lines.push('}');

  return lines.join('\n');
}

function generateIngestPipeline(
  results: PathAnalysisResult[],
  sensitiveFindings: SensitiveFinding[],
  sampleAnalysis?: LogSampleAnalysis
): string {
  const processors: Record<string, Record<string, unknown>>[] = [];

  // Add JSON parsing if needed
  if (sampleAnalysis?.detectedFormat === 'json') {
    processors.push({
      json: {
        field: 'message',
        target_field: 'parsed',
        ignore_failure: true,
      },
    });
  }

  // Add grok parsing for non-JSON formats
  if (sampleAnalysis?.detectedFormat && sampleAnalysis.detectedFormat !== 'json') {
    let pattern = '%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}';

    if (sampleAnalysis.detectedFormat === 'apache') {
      pattern = '%{COMBINEDAPACHELOG}';
    } else if (sampleAnalysis.detectedFormat === 'syslog') {
      pattern = '%{SYSLOGBASE} %{GREEDYDATA:syslog_message}';
    }

    processors.push({
      grok: {
        field: 'message',
        patterns: [pattern],
        ignore_failure: true,
      },
    });
  }

  // Add timestamp parsing
  if (sampleAnalysis?.timeFormat) {
    const logstashTimeFormat = convertSplunkToLogstashTimeFormat(sampleAnalysis.timeFormat);
    processors.push({
      date: {
        field: 'timestamp',
        target_field: '@timestamp',
        formats: [logstashTimeFormat],
        ignore_failure: true,
      },
    });
  }

  // Add data masking for sensitive findings
  if (sensitiveFindings.length > 0) {
    for (const finding of sensitiveFindings) {
      if (finding.riskLevel === 'high' || finding.riskLevel === 'critical') {
        processors.push({
          gsub: {
            field: 'message',
            pattern: finding.pattern,
            replacement: finding.maskFormat,
            ignore_failure: true,
          },
        });
      }
    }
  }

  // Add custom fields
  processors.push({
    set: {
      field: 'event.dataset',
      value: results[0]?.sourcetype || 'generic',
    },
  });

  if (sampleAnalysis) {
    processors.push({
      set: {
        field: 'event.platform',
        value: sampleAnalysis.detectedPlatform,
      },
    });
    processors.push({
      set: {
        field: 'event.format',
        value: sampleAnalysis.detectedFormat,
      },
    });
  }

  const pipeline = {
    description: 'LogOnboard-AI generated ingest pipeline',
    processors,
  };

  return JSON.stringify(pipeline, null, 2);
}

function generateIndexTemplate(
  results: PathAnalysisResult[],
  sampleAnalysis?: LogSampleAnalysis
): string {
  const template = {
    index_patterns: results.map((r) => `filebeat-${r.sourcetype}-*`),
    template: {
      settings: {
        number_of_shards: 1,
        number_of_replicas: 1,
        'index.lifecycle.name': 'logs',
        'index.lifecycle.rollover_alias': 'logs',
      },
      mappings: {
        properties: {
          '@timestamp': { type: 'date' },
          message: { type: 'text' },
          level: { type: 'keyword' },
          sourcetype: { type: 'keyword' },
          index_name: { type: 'keyword' },
          'event.dataset': { type: 'keyword' },
          'event.platform': { type: 'keyword' },
          'event.format': { type: 'keyword' },
          'host.name': { type: 'keyword' },
          'agent.version': { type: 'keyword' },
        },
      },
    },
  };

  // Add detected fields from sample analysis
  if (sampleAnalysis && sampleAnalysis.detectedFields.length > 0) {
    for (const field of sampleAnalysis.detectedFields.slice(0, 20)) {
      // Limit to 20 fields
      (template.template.mappings.properties as Record<string, unknown>)[field] = {
        type: 'keyword',
      };
    }
  }

  return JSON.stringify(template, null, 2);
}

// Helper function to convert Splunk TIME_FORMAT to Logstash/Elasticsearch format
function convertSplunkToLogstashTimeFormat(splunkFormat: string): string {
  return (
    splunkFormat
      .replace(/%Y/g, 'yyyy')
      .replace(/%m/g, 'MM')
      .replace(/%d/g, 'dd')
      .replace(/%H/g, 'HH')
      .replace(/%M/g, 'mm')
      .replace(/%S/g, 'ss')
      .replace(/%3N/g, 'SSS') // milliseconds
      .replace(/%6N/g, 'SSSSSS') // microseconds
      .replace(/%9N/g, 'SSSSSSSSS') // nanoseconds
      .replace(/%z/g, 'Z') // timezone
      .replace(/%b/g, 'MMM') // abbreviated month
      // Add more conversions as needed
      .replace(/<NEEDS_SAMPLE>/g, 'ISO8601') // fallback
  );
}
