import type { PathAnalysisResult, ElasticConfig } from '@/types/logonboard';

// Elastic/ECS Configuration Generator
// Based on: https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html

export function generateElasticConfig(results: PathAnalysisResult[]): ElasticConfig {
  return {
    filebeatYml: generateFilebeatYml(results),
    ingestPipeline: generateIngestPipeline(results),
    indexTemplate: generateIndexTemplate(results),
  };
}

function generateFilebeatYml(results: PathAnalysisResult[]): string {
  const lines: string[] = [
    '# Filebeat Configuration',
    '# Generated by LogOnboard-AI',
    '# Docs: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html',
    '',
    'filebeat.inputs:',
  ];

  const grouped = groupByModule(results);

  for (const [module, paths] of grouped.entries()) {
    lines.push('');
    lines.push(`# ${module} logs`);
    lines.push('- type: filestream');
    lines.push(`  id: ${module.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-logs`);
    lines.push('  enabled: true');
    lines.push('  paths:');

    for (const result of paths) {
      lines.push(`    - ${result.path}`);
    }

    // Add ECS fields
    lines.push('  fields:');
    lines.push(`    event.module: ${module}`);
    lines.push('  fields_under_root: true');
  }

  lines.push('');
  lines.push('# Elasticsearch output');
  lines.push('output.elasticsearch:');
  lines.push('  hosts: ["localhost:9200"]');
  lines.push('  # index: "logs-%{[event.module]}-%{+yyyy.MM.dd}"');
  lines.push('');
  lines.push('# Processors');
  lines.push('processors:');
  lines.push('  - add_host_metadata: ~');
  lines.push('  - add_cloud_metadata: ~');
  lines.push('  - add_docker_metadata: ~');
  lines.push('  - add_kubernetes_metadata: ~');

  return lines.join('\n');
}

function generateIngestPipeline(results: PathAnalysisResult[]): string {
  const modules = [...new Set(results.map((r) => r.category))];

  const pipeline = {
    description: 'LogOnboard-AI generated ingest pipeline',
    processors: modules.map((module) => ({
      set: {
        field: 'event.module',
        value: module,
        if: `ctx?.log?.file?.path != null && ctx.log.file.path.contains('${module}')`,
      },
    })),
    on_failure: [
      {
        set: {
          field: 'error.message',
          value: '{{ _ingest.on_failure_message }}',
        },
      },
    ],
  };

  return JSON.stringify(pipeline, null, 2);
}

function generateIndexTemplate(results: PathAnalysisResult[]): string {
  const sourcetypes = [...new Set(results.map((r) => r.sourcetype))];

  const template = {
    index_patterns: ['logs-*'],
    template: {
      settings: {
        number_of_shards: 1,
        number_of_replicas: 1,
      },
      mappings: {
        properties: {
          '@timestamp': { type: 'date' },
          message: { type: 'text' },
          'log.level': { type: 'keyword' },
          'event.module': { type: 'keyword' },
          'event.dataset': { type: 'keyword' },
          'host.name': { type: 'keyword' },
          'source.ip': { type: 'ip' },
          'destination.ip': { type: 'ip' },
          'user.name': { type: 'keyword' },
        },
      },
    },
    _meta: {
      description: 'LogOnboard-AI generated template',
      sourcetypes: sourcetypes,
    },
  };

  return JSON.stringify(template, null, 2);
}

function groupByModule(results: PathAnalysisResult[]): Map<string, PathAnalysisResult[]> {
  const grouped = new Map<string, PathAnalysisResult[]>();

  for (const result of results) {
    // Map sourcetype to Elastic module name
    const elasticModule = mapToElasticModule(result.sourcetype);
    const existing = grouped.get(elasticModule) || [];
    existing.push(result);
    grouped.set(elasticModule, existing);
  }

  return grouped;
}

function mapToElasticModule(sourcetype: string): string {
  const mapping: Record<string, string> = {
    access_combined: 'apache',
    'apache:error': 'apache',
    'nginx:plus:access': 'nginx',
    'nginx:plus:error': 'nginx',
    syslog: 'system',
    linux_secure: 'system',
    'linux:audit': 'auditd',
    'WinEventLog:Security': 'winlog',
    'WinEventLog:System': 'winlog',
    'WinEventLog:Application': 'winlog',
    'mysql:error': 'mysql',
    'mysql:slowquery': 'mysql',
    postgresql: 'postgresql',
    mongodb: 'mongodb',
    docker: 'docker',
    'kube:container:logs': 'kubernetes',
    'pan:traffic': 'panw',
    'pan:threat': 'panw',
    'cisco:asa': 'cisco',
  };

  return mapping[sourcetype] || 'generic';
}
