// Multi-SIEM Generator Index
// Export all SIEM-specific generators

export { generateElasticConfig } from './elastic-generator';
export { generateSentinelConfig } from './sentinel-generator';
export { generateQRadarConfig } from './qradar-generator';
export { generateCriblConfig } from './cribl-generator';

import type {
  PathAnalysisResult,
  GeneratedConfig,
  SIEM,
  SensitiveFinding,
  AnalyzeOptions,
} from '@/types/logonboard';
import { generateSplunkConfigs } from '../splunk-generator';
import { generateElasticConfig } from './elastic-generator';
import { generateSentinelConfig } from './sentinel-generator';
import { generateQRadarConfig } from './qradar-generator';
import { generateCriblConfig } from './cribl-generator';

/**
 * Generate configuration for any supported SIEM
 */
export function generateConfigForSIEM(
  results: PathAnalysisResult[],
  siem: SIEM,
  sensitiveFindings: SensitiveFinding[]
): GeneratedConfig {
  const baseConfig: GeneratedConfig = {
    inputsConf: '',
    propsConf: '',
    transformsConf: '',
    readme: '',
    metadata: {
      generatedAt: new Date().toISOString(),
      version: '1.0.0',
      pathCount: results.length,
      sourcetypes: [...new Set(results.map((r) => r.sourcetype))],
      indexes: [...new Set(results.map((r) => r.index))],
      sensitiveFindings: sensitiveFindings,
      warnings: [],
    },
    siem,
  };

  // Default options for Splunk generator
  const defaultOptions: AnalyzeOptions = {
    runSensitiveScan: true,
    includeDomainsInConfigs: false,
    outputFormat: 'txt',
  };

  switch (siem) {
    case 'splunk': {
      const splunkConfigs = generateSplunkConfigs(results, sensitiveFindings, defaultOptions);
      return {
        ...baseConfig,
        inputsConf: splunkConfigs.inputsConf,
        propsConf: splunkConfigs.propsConf,
        transformsConf: splunkConfigs.transformsConf,
        readme: splunkConfigs.readme,
        metadata: splunkConfigs.metadata,
      };
    }

    case 'elastic': {
      const elasticConfig = generateElasticConfig(results);
      return {
        ...baseConfig,
        inputsConf: elasticConfig.filebeatYml,
        propsConf: elasticConfig.ingestPipeline,
        transformsConf: elasticConfig.indexTemplate,
        readme: generateElasticReadme(results),
        elastic: elasticConfig,
      };
    }

    case 'sentinel': {
      const sentinelConfig = generateSentinelConfig(results);
      return {
        ...baseConfig,
        inputsConf: sentinelConfig.dataCollectionRule,
        propsConf: sentinelConfig.analyticsRules,
        transformsConf: sentinelConfig.workbook,
        readme: generateSentinelReadme(results),
        sentinel: sentinelConfig,
      };
    }

    case 'qradar': {
      const qradarConfig = generateQRadarConfig(results);
      return {
        ...baseConfig,
        inputsConf: qradarConfig.logSourceExtension,
        propsConf: qradarConfig.dsmConfig,
        transformsConf: '',
        readme: generateQRadarReadme(results),
        qradar: qradarConfig,
      };
    }

    case 'cribl': {
      const criblConfig = generateCriblConfig(results);
      return {
        ...baseConfig,
        inputsConf: criblConfig.routes,
        propsConf: criblConfig.pipelines,
        transformsConf: criblConfig.packs,
        readme: generateCriblReadme(results),
        cribl: criblConfig,
      };
    }

    default:
      return baseConfig;
  }
}

function generateElasticReadme(results: PathAnalysisResult[]): string {
  return `# Elastic Stack Configuration
Generated by LogOnboard-AI

## Files Included
- filebeat.yml - Filebeat input configuration
- ingest-pipeline.json - Elasticsearch ingest pipeline
- index-template.json - Index template with ECS mappings

## Installation
1. Copy filebeat.yml to /etc/filebeat/
2. Import ingest pipeline: PUT _ingest/pipeline/logonboard
3. Import index template: PUT _index_template/logonboard

## Documentation
- Filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/
- ECS: https://www.elastic.co/guide/en/ecs/current/

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}

function generateSentinelReadme(results: PathAnalysisResult[]): string {
  return `# Microsoft Sentinel Configuration
Generated by LogOnboard-AI

## Files Included
- data-collection-rule.json - ARM template for DCR
- analytics-rules.json - KQL-based detection rules
- workbook.json - Dashboard workbook

## Installation
1. Deploy DCR via Azure Portal or CLI
2. Import analytics rules in Sentinel
3. Import workbook for visualization

## Documentation
- Data Connectors: https://learn.microsoft.com/en-us/azure/sentinel/connect-data-sources
- KQL: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}

function generateQRadarReadme(results: PathAnalysisResult[]): string {
  return `# IBM QRadar Configuration
Generated by LogOnboard-AI

## Files Included
- log-source-extension.xml - Custom log source extension
- dsm-config.txt - DSM configuration guide

## Installation
1. Import LSX via Admin > DSM Editor
2. Create log sources using the DSM mappings
3. Configure event forwarding

## Documentation
- DSM Guide: https://www.ibm.com/docs/en/dsm
- Log Sources: https://www.ibm.com/docs/en/qradar-on-cloud

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}

function generateCriblReadme(results: PathAnalysisResult[]): string {
  return `# Cribl Stream Configuration
Generated by LogOnboard-AI

## Files Included
- routes.yml - Data routing configuration
- pipelines.yml - Processing pipelines
- pack.yml - Portable pack manifest

## Installation
1. Import pack via Packs > Add Pack
2. Configure Sources (Syslog, File, etc.)
3. Configure Destinations (Splunk, Elastic, S3, etc.)
4. Enable routes

## Documentation
- Packs: https://docs.cribl.io/stream/packs/
- Routes: https://docs.cribl.io/stream/routes/

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}
