// Multi-SIEM Generator Index
// Export all SIEM-specific generators

export { generateElasticConfigs } from './elastic-generator';
export { generateSentinelConfig } from './sentinel-generator';
export { generateQRadarConfig } from './qradar-generator';
export { generateCriblConfig } from './cribl-generator';

import type {
  PathAnalysisResult,
  GeneratedConfig,
  SIEM,
  SensitiveFinding,
  AnalyzeOptions,
  LogSampleAnalysis,
} from '@/types/logonboard';
import { generateSplunkConfigs } from '../splunk-generator';
import { generateElasticConfigs } from './elastic-generator';
import { generateSentinelConfig } from './sentinel-generator';
import { generateQRadarConfig } from './qradar-generator';
import { generateCriblConfig } from './cribl-generator';

/**
 * Generate configuration for any supported SIEM
 * @param sampleAnalysis - Optional log sample analysis to enhance props.conf generation
 */
export function generateConfigForSIEM(
  results: PathAnalysisResult[],
  siem: SIEM,
  sensitiveFindings: SensitiveFinding[],
  sampleAnalysis?: LogSampleAnalysis
): GeneratedConfig {
  const baseConfig: GeneratedConfig = {
    inputsConf: '',
    propsConf: '',
    transformsConf: '',
    readme: '',
    metadata: {
      generatedAt: new Date().toISOString(),
      version: '1.0.0',
      pathCount: results.length,
      sourcetypes: [...new Set(results.map((r) => r.sourcetype))],
      indexes: [...new Set(results.map((r) => r.index))],
      sensitiveFindings: sensitiveFindings,
      warnings: [],
    },
    siem,
  };

  // Default options for Splunk generator
  const defaultOptions: AnalyzeOptions = {
    runSensitiveScan: true,
    includeDomainsInConfigs: false,
    outputFormat: 'txt',
  };

  switch (siem) {
    case 'splunk': {
      const splunkConfigs = generateSplunkConfigs(
        results,
        sensitiveFindings,
        defaultOptions,
        sampleAnalysis
      );
      return {
        ...baseConfig,
        inputsConf: splunkConfigs.inputsConf,
        propsConf: splunkConfigs.propsConf,
        transformsConf: splunkConfigs.transformsConf,
        readme: splunkConfigs.readme,
        metadata: splunkConfigs.metadata,
      };
    }

    case 'elastic': {
      const elasticConfig = generateElasticConfigs(
        results,
        sensitiveFindings,
        defaultOptions,
        sampleAnalysis
      );
      return {
        ...baseConfig,
        inputsConf: elasticConfig.filebeatYml,
        propsConf: elasticConfig.logstashConf,
        transformsConf: elasticConfig.ingestPipeline,
        readme: generateElasticReadme(results, sampleAnalysis),
        elastic: elasticConfig,
      };
    }

    case 'sentinel': {
      const sentinelConfig = generateSentinelConfig(results);
      return {
        ...baseConfig,
        inputsConf: sentinelConfig.dataCollectionRule,
        propsConf: sentinelConfig.analyticsRules,
        transformsConf: sentinelConfig.workbook,
        readme: generateSentinelReadme(results),
        sentinel: sentinelConfig,
      };
    }

    case 'qradar': {
      const qradarConfig = generateQRadarConfig(results);
      return {
        ...baseConfig,
        inputsConf: qradarConfig.logSourceExtension,
        propsConf: qradarConfig.dsmConfig,
        transformsConf: '',
        readme: generateQRadarReadme(results),
        qradar: qradarConfig,
      };
    }

    case 'cribl': {
      const criblConfig = generateCriblConfig(results);
      return {
        ...baseConfig,
        inputsConf: criblConfig.routes,
        propsConf: criblConfig.pipelines,
        transformsConf: criblConfig.packs,
        readme: generateCriblReadme(results),
        cribl: criblConfig,
      };
    }

    default:
      return baseConfig;
  }
}

function generateElasticReadme(
  results: PathAnalysisResult[],
  sampleAnalysis?: LogSampleAnalysis
): string {
  const platformInfo = sampleAnalysis
    ? `\n## Detected Log Information\n- Platform: ${sampleAnalysis.detectedPlatform.toUpperCase()}\n- Format: ${sampleAnalysis.detectedFormat.toUpperCase()}\n- Confidence: ${sampleAnalysis.confidence}\n`
    : '';

  return `# Elastic Stack Configuration
Generated by LogOnboard-AI
${platformInfo}
## Files Included
- **filebeat.yml** - Filebeat log collection agent configuration
- **logstash.conf** - Logstash data processing pipeline
- **ingest-pipeline.json** - Elasticsearch ingest pipeline for index-time processing
- **index-template.json** - Index template with field mappings

## Deployment Architecture

\`\`\`
┌─────────────────┐    ┌─────────────────┐    ┌─────────────────┐
│  Log Sources    │    │    Logstash     │    │ Elasticsearch   │
│  (with Filebeat)│───▶│   (optional)    │───▶│                 │
│                 │    │                 │    │                 │
│  filebeat.yml   │    │  logstash.conf  │    │ ingest-pipeline │
│                 │    │                 │    │ index-template  │
└─────────────────┘    └─────────────────┘    └─────────────────┘
\`\`\`

## Installation Steps

### 1. Install & Configure Filebeat
\`\`\`bash
# Download Filebeat
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.19.0-linux-x86_64.tar.gz
tar xzvf filebeat-8.19.0-linux-x86_64.tar.gz

# Copy configuration
cp filebeat.yml /etc/filebeat/filebeat.yml

# Start Filebeat
sudo systemctl start filebeat
sudo systemctl enable filebeat
\`\`\`

### 2. (Optional) Install & Configure Logstash
\`\`\`bash
# Install Logstash
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
sudo apt-get install logstash

# Copy configuration
cp logstash.conf /etc/logstash/conf.d/

# Start Logstash
sudo systemctl start logstash
sudo systemctl enable logstash
\`\`\`

### 3. Import Ingest Pipeline & Index Template
\`\`\`bash
# Import ingest pipeline
curl -X PUT "localhost:9200/_ingest/pipeline/logonboard" -H 'Content-Type: application/json' -d @ingest-pipeline.json

# Import index template
curl -X PUT "localhost:9200/_index_template/logonboard" -H 'Content-Type: application/json' -d @index-template.json
\`\`\`

## Documentation
- **Filebeat**: https://www.elastic.co/guide/en/beats/filebeat/current/
- **Logstash**: https://www.elastic.co/guide/en/logstash/current/
- **Ingest Pipelines**: https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html
- **ECS (Elastic Common Schema)**: https://www.elastic.co/guide/en/ecs/current/

## Analyzed Paths
${results.map((r) => `- ${r.path} → Index: \`filebeat-${r.sourcetype}-*\` (${r.category})`).join('\n')}

## Next Steps
1. Verify Filebeat is collecting logs: Check \`/var/log/filebeat\`
2. Query Elasticsearch: \`GET filebeat-*/_search\`
3. Create Kibana dashboards for visualization
4. Set up alerting rules in Kibana

---
Generated by LogOnboard-AI on ${new Date().toISOString()}
`;
}

function generateSentinelReadme(results: PathAnalysisResult[]): string {
  return `# Microsoft Sentinel Configuration
Generated by LogOnboard-AI

## Files Included
- data-collection-rule.json - ARM template for DCR
- analytics-rules.json - KQL-based detection rules
- workbook.json - Dashboard workbook

## Installation
1. Deploy DCR via Azure Portal or CLI
2. Import analytics rules in Sentinel
3. Import workbook for visualization

## Documentation
- Data Connectors: https://learn.microsoft.com/en-us/azure/sentinel/connect-data-sources
- KQL: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}

function generateQRadarReadme(results: PathAnalysisResult[]): string {
  return `# IBM QRadar Configuration
Generated by LogOnboard-AI

## Files Included
- log-source-extension.xml - Custom log source extension
- dsm-config.txt - DSM configuration guide

## Installation
1. Import LSX via Admin > DSM Editor
2. Create log sources using the DSM mappings
3. Configure event forwarding

## Documentation
- DSM Guide: https://www.ibm.com/docs/en/dsm
- Log Sources: https://www.ibm.com/docs/en/qradar-on-cloud

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}

function generateCriblReadme(results: PathAnalysisResult[]): string {
  return `# Cribl Stream Configuration
Generated by LogOnboard-AI

## Files Included
- routes.yml - Data routing configuration
- pipelines.yml - Processing pipelines
- pack.yml - Portable pack manifest

## Installation
1. Import pack via Packs > Add Pack
2. Configure Sources (Syslog, File, etc.)
3. Configure Destinations (Splunk, Elastic, S3, etc.)
4. Enable routes

## Documentation
- Packs: https://docs.cribl.io/stream/packs/
- Routes: https://docs.cribl.io/stream/routes/

## Analyzed Paths
${results.map((r) => `- ${r.path} (${r.sourcetype})`).join('\n')}
`;
}
