import type { PathAnalysisResult, QRadarConfig } from '@/types/logonboard';

// IBM QRadar Configuration Generator
// Based on: https://www.ibm.com/docs/en/dsm

export function generateQRadarConfig(results: PathAnalysisResult[]): QRadarConfig {
  return {
    logSourceExtension: generateLogSourceExtension(results),
    dsmConfig: generateDSMConfig(results),
  };
}

function generateLogSourceExtension(results: PathAnalysisResult[]): string {
  const extensions: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- LogOnboard-AI Generated Log Source Extension -->',
    '<!-- Docs: https://www.ibm.com/docs/en/qradar-on-cloud?topic=qradar-dsm-editor-overview -->',
    '<device>',
    '  <name>LogOnboard-AI Custom</name>',
    '  <description>Auto-generated log source configuration</description>',
    '  <group>Custom</group>',
  ];

  // Generate regex patterns for each log type
  const patterns = results.map((r) => generatePatternXML(r));
  extensions.push('  <patterns>');
  extensions.push(...patterns.map((p) => '    ' + p));
  extensions.push('  </patterns>');

  extensions.push('</device>');

  return extensions.join('\n');
}

function generatePatternXML(result: PathAnalysisResult): string {
  const dsm = mapToDSM(result.sourcetype);

  return `<pattern id="${result.sourcetype.replace(/[^a-zA-Z0-9]/g, '_')}">
      <name>${result.sourcetype}</name>
      <description>Pattern for ${result.filename}</description>
      <dsm>${dsm}</dsm>
      <regex><![CDATA[.*]]></regex>
      <order>100</order>
    </pattern>`;
}

function generateDSMConfig(results: PathAnalysisResult[]): string {
  const config: string[] = [
    '# QRadar DSM Configuration',
    '# Generated by LogOnboard-AI',
    '# Import via: Admin > DSM Editor',
    '',
    '# Log Source Types:',
  ];

  const grouped = groupByDSM(results);

  for (const [dsm, paths] of grouped.entries()) {
    config.push('');
    config.push(`## ${dsm}`);
    config.push(`# DSM: ${dsm}`);
    config.push('# Paths:');
    for (const result of paths) {
      config.push(`#   - ${result.path}`);
    }
    config.push('');
    config.push(`log_source_type_name=${dsm}`);
    config.push(`log_source_identifier=${paths[0].filename}`);
    config.push('protocol=syslog');
    config.push('enabled=true');
    config.push('');
  }

  // Add LEEF format guidance
  config.push('# LEEF Format Reference');
  config.push('# LEEF:Version|Vendor|Product|Version|EventID|');
  config.push('# Example: LEEF:1.0|Microsoft|Windows|10|4624|');
  config.push('');

  // Add recommended event mappings
  config.push('# Recommended Event ID Mappings:');

  if (results.some((r) => r.sourcetype.includes('Security'))) {
    config.push('# Windows Security Events:');
    config.push('#   4624 - Successful Logon');
    config.push('#   4625 - Failed Logon');
    config.push('#   4648 - Explicit Credential Logon');
    config.push('#   4672 - Special Privileges Assigned');
  }

  if (results.some((r) => r.category === 'web')) {
    config.push('# Web Server Events:');
    config.push('#   HTTP_ACCESS - Access log entry');
    config.push('#   HTTP_ERROR - Error log entry');
  }

  return config.join('\n');
}

function groupByDSM(results: PathAnalysisResult[]): Map<string, PathAnalysisResult[]> {
  const grouped = new Map<string, PathAnalysisResult[]>();

  for (const result of results) {
    const dsm = mapToDSM(result.sourcetype);
    const existing = grouped.get(dsm) || [];
    existing.push(result);
    grouped.set(dsm, existing);
  }

  return grouped;
}

function mapToDSM(sourcetype: string): string {
  const mapping: Record<string, string> = {
    access_combined: 'Apache HTTP Server',
    'apache:error': 'Apache HTTP Server',
    'nginx:plus:access': 'NGINX HTTP Server',
    'nginx:plus:error': 'NGINX HTTP Server',
    syslog: 'Linux OS',
    linux_secure: 'Linux OS',
    'linux:audit': 'Linux OS',
    'WinEventLog:Security': 'Microsoft Windows Security Event Log',
    'WinEventLog:System': 'Microsoft Windows Security Event Log',
    'WinEventLog:Application': 'Microsoft Windows Security Event Log',
    iis: 'Microsoft IIS',
    'mysql:error': 'MySQL',
    'mysql:slowquery': 'MySQL',
    postgresql: 'PostgreSQL',
    mongodb: 'MongoDB',
    'pan:traffic': 'Palo Alto PA Series',
    'pan:threat': 'Palo Alto PA Series',
    'cisco:asa': 'Cisco Adaptive Security Appliance',
    docker: 'Universal LEEF',
    'kube:container:logs': 'Universal LEEF',
  };

  return mapping[sourcetype] || 'Universal LEEF';
}
