import type { PathAnalysisResult, SentinelConfig } from '@/types/logonboard';

// Microsoft Sentinel Configuration Generator
// Based on: https://learn.microsoft.com/en-us/azure/sentinel/data-connectors-reference

export function generateSentinelConfig(results: PathAnalysisResult[]): SentinelConfig {
  return {
    dataCollectionRule: generateDataCollectionRule(results),
    analyticsRules: generateAnalyticsRules(results),
    workbook: generateWorkbook(results),
  };
}

function generateDataCollectionRule(results: PathAnalysisResult[]): string {
  const streams = [...new Set(results.map((r) => mapToSentinelTable(r.sourcetype)))];

  const dcr = {
    $schema: 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#',
    contentVersion: '1.0.0.0',
    parameters: {
      dataCollectionRuleName: {
        type: 'string',
        defaultValue: 'LogOnboard-DCR',
      },
      location: {
        type: 'string',
        defaultValue: '[resourceGroup().location]',
      },
      workspaceResourceId: {
        type: 'string',
        metadata: {
          description: 'Log Analytics workspace resource ID',
        },
      },
    },
    resources: [
      {
        type: 'Microsoft.Insights/dataCollectionRules',
        apiVersion: '2022-06-01',
        name: "[parameters('dataCollectionRuleName')]",
        location: "[parameters('location')]",
        properties: {
          description: 'Data collection rule generated by LogOnboard-AI',
          dataSources: {
            syslog: results.some((r) => r.category === 'os' || r.category === 'security')
              ? [
                  {
                    name: 'syslogDataSource',
                    streams: ['Microsoft-Syslog'],
                    facilityNames: [
                      'auth',
                      'authpriv',
                      'daemon',
                      'kern',
                      'syslog',
                      'user',
                      'local0',
                    ],
                    logLevels: [
                      'Debug',
                      'Info',
                      'Notice',
                      'Warning',
                      'Error',
                      'Critical',
                      'Alert',
                      'Emergency',
                    ],
                  },
                ]
              : [],
            windowsEventLogs: results.some((r) => r.sourcetype.includes('WinEventLog'))
              ? [
                  {
                    name: 'windowsEventLogs',
                    streams: ['Microsoft-SecurityEvent'],
                    xPathQueries: [
                      'Security!*[System[(EventID=4624 or EventID=4625 or EventID=4648)]]',
                    ],
                  },
                ]
              : [],
          },
          destinations: {
            logAnalytics: [
              {
                workspaceResourceId: "[parameters('workspaceResourceId')]",
                name: 'logAnalyticsDestination',
              },
            ],
          },
          dataFlows: streams.map((stream) => ({
            streams: [`Microsoft-${stream}`],
            destinations: ['logAnalyticsDestination'],
            transformKql: 'source',
            outputStream: `Microsoft-${stream}`,
          })),
        },
      },
    ],
  };

  return JSON.stringify(dcr, null, 2);
}

function generateAnalyticsRules(results: PathAnalysisResult[]): string {
  const rules: object[] = [];

  // Add rules based on detected log types
  if (results.some((r) => r.sourcetype.includes('Security'))) {
    rules.push({
      name: 'Failed Login Attempts',
      description: 'Detects multiple failed login attempts',
      query: `SecurityEvent
| where EventID == 4625
| summarize FailedAttempts = count() by TargetAccount, IpAddress, bin(TimeGenerated, 5m)
| where FailedAttempts > 5`,
      severity: 'Medium',
      triggerOperator: 'GreaterThan',
      triggerThreshold: 0,
    });
  }

  if (results.some((r) => r.category === 'web')) {
    rules.push({
      name: 'Web Server Errors',
      description: 'Detects high rate of web server errors',
      query: `Syslog
| where ProcessName has_any ("apache", "nginx", "httpd")
| where SeverityLevel in ("err", "error", "crit", "critical")
| summarize ErrorCount = count() by Computer, bin(TimeGenerated, 5m)
| where ErrorCount > 10`,
      severity: 'Low',
      triggerOperator: 'GreaterThan',
      triggerThreshold: 0,
    });
  }

  return JSON.stringify(rules, null, 2);
}

function generateWorkbook(results: PathAnalysisResult[]): string {
  const categories = [...new Set(results.map((r) => r.category))];

  const workbook = {
    version: 'Notebook/1.0',
    items: [
      {
        type: 1,
        content: {
          json: '# LogOnboard-AI Dashboard\n\nGenerated workbook for monitoring ingested logs.',
        },
      },
      ...categories.map((category) => ({
        type: 3,
        content: {
          version: 'KqlItem/1.0',
          query: `union withsource=TableName *
| where TimeGenerated > ago(24h)
| summarize Count = count() by TableName
| order by Count desc`,
          size: 1,
          title: `${category.charAt(0).toUpperCase() + category.slice(1)} Logs`,
          queryType: 0,
          visualization: 'piechart',
        },
      })),
    ],
  };

  return JSON.stringify(workbook, null, 2);
}

function mapToSentinelTable(sourcetype: string): string {
  const mapping: Record<string, string> = {
    access_combined: 'Syslog',
    'apache:error': 'Syslog',
    'nginx:plus:access': 'Syslog',
    'nginx:plus:error': 'Syslog',
    syslog: 'Syslog',
    linux_secure: 'Syslog',
    'linux:audit': 'AuditLogs',
    'WinEventLog:Security': 'SecurityEvent',
    'WinEventLog:System': 'Event',
    'WinEventLog:Application': 'Event',
    iis: 'W3CIISLog',
    'pan:traffic': 'CommonSecurityLog',
    'pan:threat': 'CommonSecurityLog',
    'cisco:asa': 'CommonSecurityLog',
    'aws:cloudtrail': 'AWSCloudTrail',
  };

  return mapping[sourcetype] || 'Custom_CL';
}
