import type {
  PathAnalysisResult,
  SensitiveFinding,
  GeneratedConfig,
  ConfigMetadata,
  AnalyzeOptions,
  LogSampleAnalysis,
} from '@/types/logonboard';
import { getPropsTemplate } from './knowledge-base';
import { groupBySourcetype } from './path-analyzer';
import { getTransformsForMasking } from './sensitive-scanner';

// Splunk Config Generator - Creates inputs.conf, props.conf, transforms.conf

export function generateSplunkConfigs(
  analysisResults: PathAnalysisResult[],
  sensitiveFindings: SensitiveFinding[],
  options: AnalyzeOptions,
  sampleAnalysis?: LogSampleAnalysis
): GeneratedConfig {
  const inputsConf = generateInputsConf(analysisResults);
  const propsConf = generatePropsConf(analysisResults, sampleAnalysis);
  const transformsConf = generateTransformsConf(sensitiveFindings, options);
  const readme = generateReadme(analysisResults, sensitiveFindings, options, sampleAnalysis);
  const metadata = generateMetadata(analysisResults, sensitiveFindings);

  return {
    inputsConf,
    propsConf,
    transformsConf,
    readme,
    metadata,
  };
}

function generateInputsConf(results: PathAnalysisResult[]): string {
  const lines: string[] = [
    '# inputs.conf - Generated by LogOnboard-AI',
    '#',
    '# DEPLOYMENT: Universal Forwarder (UF)',
    '# Deploy this file to each log source endpoint',
    '# Path: $SPLUNK_HOME/etc/apps/<app_name>/local/inputs.conf',
    '#',
    '# Best Practice: Use deployment server to push to forwarders',
    '# Ref: https://docs.splunk.com/Documentation/Splunk/latest/Forwarding/Deploytheuniversalforwarder',
    '',
  ];

  for (const result of results) {
    lines.push(`[monitor://${result.path}]`);
    lines.push(`sourcetype = ${result.sourcetype}`);
    lines.push(`index = ${result.index}`);
    lines.push(`disabled = 0`);

    if (result.confidence === 'low') {
      lines.push(`# WARNING: Low confidence match - please verify sourcetype`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

function generatePropsConf(
  results: PathAnalysisResult[],
  sampleAnalysis?: LogSampleAnalysis
): string {
  const hasSampleAnalysis = sampleAnalysis && sampleAnalysis.confidence !== 'low';

  const lines: string[] = [
    '# props.conf - Generated by LogOnboard-AI',
    '#',
    '# DEPLOYMENT: Heavy Forwarder (HF) or Indexer',
    '# - HF: For parsing BEFORE data reaches indexers (recommended)',
    '# - Indexer: For index-time field extractions',
    '# - Search Head: For search-time extractions only (not recommended for parsing)',
    '#',
    '# Path: $SPLUNK_HOME/etc/apps/<app_name>/local/props.conf',
    '# Ref: https://docs.splunk.com/Documentation/Splunk/latest/Admin/Propsconf',
    '#',
  ];

  if (hasSampleAnalysis) {
    lines.push(
      `# TIME_FORMAT and KV_MODE derived from log sample analysis (${sampleAnalysis.confidence} confidence)`
    );
  } else {
    lines.push('# NOTE: TIME_FORMAT may need adjustment based on actual log samples');
  }
  lines.push('');

  const grouped = groupBySourcetype(results);

  for (const [sourcetype] of grouped) {
    const template = getPropsTemplate(sourcetype);

    lines.push(`[${sourcetype}]`);
    lines.push(`# Category: ${template.category}`);
    lines.push(`SHOULD_LINEMERGE = ${template.SHOULD_LINEMERGE}`);

    // Use sample analysis LINE_BREAKER if available, otherwise use template
    const lineBreaker =
      hasSampleAnalysis && sampleAnalysis.lineBreaker
        ? sampleAnalysis.lineBreaker
        : template.LINE_BREAKER;
    lines.push(`LINE_BREAKER = ${lineBreaker}`);

    // Use sample analysis TIME_PREFIX if available
    const timePrefix =
      hasSampleAnalysis && sampleAnalysis.timePrefix
        ? sampleAnalysis.timePrefix
        : template.TIME_PREFIX;
    if (timePrefix) {
      lines.push(`TIME_PREFIX = ${timePrefix}`);
    }

    // Use sample analysis TIME_FORMAT if available, otherwise use template
    const timeFormat =
      hasSampleAnalysis && sampleAnalysis.timeFormat
        ? sampleAnalysis.timeFormat
        : template.TIME_FORMAT;
    lines.push(`TIME_FORMAT = ${timeFormat}`);

    // Use sample analysis MAX_TIMESTAMP_LOOKAHEAD if available
    const maxLookahead =
      hasSampleAnalysis && sampleAnalysis.maxTimestampLookahead > 0
        ? sampleAnalysis.maxTimestampLookahead.toString()
        : template.MAX_TIMESTAMP_LOOKAHEAD;
    lines.push(`MAX_TIMESTAMP_LOOKAHEAD = ${maxLookahead}`);

    // Use sample analysis KV_MODE if available
    const kvMode = hasSampleAnalysis ? sampleAnalysis.kvMode : template.KV_MODE;
    lines.push(`KV_MODE = ${kvMode}`);
    lines.push(`TRUNCATE = ${template.TRUNCATE}`);

    // Add detected fields as a comment if available
    if (hasSampleAnalysis && sampleAnalysis.detectedFields.length > 0) {
      lines.push(
        `# Detected fields: ${sampleAnalysis.detectedFields.slice(0, 10).join(', ')}${sampleAnalysis.detectedFields.length > 10 ? '...' : ''}`
      );
    }

    if (timeFormat === '<NEEDS_SAMPLE>' && !hasSampleAnalysis) {
      lines.push(`# NOTE: TIME_FORMAT requires a log sample for accurate configuration`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

function generateTransformsConf(findings: SensitiveFinding[], options: AnalyzeOptions): string {
  const lines: string[] = [
    '# transforms.conf - Generated by LogOnboard-AI',
    '#',
    '# DEPLOYMENT: Heavy Forwarder (HF) or Indexer',
    '# Deploy alongside props.conf - data masking/transformation happens here',
    '#',
    '# IMPORTANT: For data masking to work BEFORE indexing:',
    '# - Deploy to HF (recommended) or Indexer',
    '# - Masking at Search Head only hides data in search results,',
    '#   but raw data is still stored unmasked in indexes!',
    '#',
    '# Path: $SPLUNK_HOME/etc/apps/<app_name>/local/transforms.conf',
    '# Ref: https://docs.splunk.com/Documentation/Splunk/latest/Admin/Transformsconf',
    '',
  ];

  if (!options.runSensitiveScan || findings.length === 0) {
    lines.push('# No sensitive data transforms required');
    lines.push('# Enable sensitive scan to generate masking transforms');
    return lines.join('\n');
  }

  const transformLines = getTransformsForMasking(findings);

  if (transformLines.length === 0) {
    lines.push('# No high-risk patterns detected requiring masking');
  } else {
    lines.push(...transformLines);
    lines.push('');
    lines.push('# Apply transforms in props.conf:');
    lines.push('# [your_sourcetype]');
    lines.push('# TRANSFORMS-mask = mask_domain, mask_email, ...');
  }

  return lines.join('\n');
}

function generateReadme(
  results: PathAnalysisResult[],
  findings: SensitiveFinding[],
  options: AnalyzeOptions,
  _sampleAnalysis?: LogSampleAnalysis
): string {
  const lines: string[] = [
    '# LogOnboard-AI Configuration Bundle',
    '',
    '## Overview',
    `Generated: ${new Date().toISOString()}`,
    `Paths analyzed: ${results.length}`,
    `Unique sourcetypes: ${new Set(results.map((r) => r.sourcetype)).size}`,
    `Unique indexes: ${new Set(results.map((r) => r.index)).size}`,
    '',
    '## Files Included & Deployment Locations',
    '',
    '| File | Deploy To | Purpose |',
    '|------|-----------|---------|',
    '| `inputs.conf` | **Universal Forwarder** | Monitor stanzas - deploy to each log source |',
    '| `props.conf` | **Heavy Forwarder/Indexer** | Parsing config - where data gets parsed |',
    '| `transforms.conf` | **Heavy Forwarder/Indexer** | Data masking - MUST be before indexing! |',
    '',
    '## Deployment Architecture',
    '',
    '```',
    '┌─────────────────┐    ┌─────────────────┐    ┌─────────────────┐',
    '│  Log Sources    │    │ Heavy Forwarder │    │    Indexers     │',
    '│  (with UF)      │───▶│   (optional)    │───▶│                 │',
    '│                 │    │                 │    │                 │',
    '│  inputs.conf    │    │  props.conf     │    │  (or props.conf │',
    '│                 │    │  transforms.conf│    │   here instead) │',
    '└─────────────────┘    └─────────────────┘    └─────────────────┘',
    '```',
    '',
    '### Best Practices',
    '',
    '- **inputs.conf**: Always on Universal Forwarders where logs originate',
    '- **props.conf + transforms.conf**: ',
    '  - Heavy Forwarder (HF) = Parse/mask BEFORE data reaches indexers (recommended)',
    '  - Indexer = Parse at index time (acceptable)',
    '  - Search Head = Search-time only (NOT for masking - raw data still stored!)',
    '',
    '## Installation Steps',
    '',
    '1. **Review configurations** - Verify paths and sourcetypes are correct',
    '2. **Create a Splunk app** on each deployment target:',
    '   ```',
    '   mkdir -p $SPLUNK_HOME/etc/apps/my_onboarding/local',
    '   ```',
    '3. **Deploy configs to correct locations**:',
    '   - inputs.conf → Universal Forwarders',
    '   - props.conf + transforms.conf → Heavy Forwarder or Indexer',
    '4. **Use Deployment Server** to push to forwarders at scale',
    '5. **Restart Splunk** or run: `$SPLUNK_HOME/bin/splunk reload deploy-server`',
    '6. **Verify data ingestion** in Search & Reporting',
    '',
    '## Path Analysis Summary',
    '',
    '| Path | Sourcetype | Index | Confidence |',
    '|------|------------|-------|------------|',
  ];

  for (const result of results) {
    const truncatedPath = result.path.length > 50 ? '...' + result.path.slice(-47) : result.path;
    lines.push(
      `| ${truncatedPath} | ${result.sourcetype} | ${result.index} | ${result.confidence} |`
    );
  }

  lines.push('');

  if (options.runSensitiveScan && findings.length > 0) {
    lines.push('## Sensitive Data Findings');
    lines.push('');
    lines.push('| Pattern | Description | Risk | Count |');
    lines.push('|---------|-------------|------|-------|');

    for (const finding of findings) {
      lines.push(
        `| ${finding.pattern} | ${finding.description} | ${finding.riskLevel} | ${finding.count} |`
      );
    }

    lines.push('');
    lines.push('**Action Required**: Review transforms.conf for masking configurations.');
  }

  lines.push('');
  lines.push('## Notes');
  lines.push('');
  lines.push('- TIME_FORMAT fields marked as `<NEEDS_SAMPLE>` require actual log samples');
  lines.push('- Low confidence matches should be manually verified');
  lines.push('- Test in a development environment before production deployment');
  lines.push('');
  lines.push('---');
  lines.push('Generated by LogOnboard-AI');

  return lines.join('\n');
}

function generateMetadata(
  results: PathAnalysisResult[],
  findings: SensitiveFinding[]
): ConfigMetadata {
  const sourcetypes = [...new Set(results.map((r) => r.sourcetype))];
  const indexes = [...new Set(results.map((r) => r.index))];

  const warnings: string[] = [];

  const lowConfidence = results.filter((r) => r.confidence === 'low');
  if (lowConfidence.length > 0) {
    warnings.push(`${lowConfidence.length} path(s) have low confidence matches`);
  }

  const needsSample = results.filter((r) => {
    const template = getPropsTemplate(r.sourcetype);
    return template.TIME_FORMAT === '<NEEDS_SAMPLE>';
  });
  if (needsSample.length > 0) {
    warnings.push(`${needsSample.length} sourcetype(s) need log samples for TIME_FORMAT`);
  }

  const criticalFindings = findings.filter((f) => f.riskLevel === 'critical');
  if (criticalFindings.length > 0) {
    warnings.push(`${criticalFindings.length} critical sensitive data pattern(s) detected`);
  }

  return {
    generatedAt: new Date().toISOString(),
    version: '0.2.0',
    pathCount: results.length,
    sourcetypes,
    indexes,
    sensitiveFindings: findings,
    warnings,
  };
}
